<?php

namespace App\Enums;

enum WhatsappTemplating:string
{
    case CANCEL_APPOINTMENT = 'APPOINTMENT_CANCEL';
    case COMPLETED_APPOINTMENT = 'APPOINTMENT_COMPLETED';
    case CONFIRM_APPOINTMENT = 'APPOINTMENT_CONFIRM';
    case REMINDER_APPOINTMENT = 'APPOINTMENT_REMINDER';
    case RESCHEDULE_APPOINTMENT = 'APPOINTMENT_RESCHEDULE';
    case DOCTOR_ON_LEAVE = 'DOCTOR_ON_LEAVE';
}
